### PR TITLE
features and fixes: many

### PR DESCRIPTION
**Pull request by cofin**
I wanted to open this PR so that you can weigh in on the current state of the repo/service/library updates I've made so far.

This fixes:
- #290 (Upgrades to the recent version that contains the async `refresh` fix that was recently released.)
- #286 
- #269 (works perfectly in the environment I've been running this on)
- #267 
- #49 

New features:
- updates to the service and repo pattern for passing in joins
- Additional methods
- Slug Model and slug model lookup
- Worker heartbeat decorator (`@monitored_job`)
- Sluggify method for slugging data values
- Ruff integration for linting

Feel free to pick and/or reject any of these things.

### CODE REVIEW

**Comment by peterschutt** [comment]
Wow, you've been busy! I'm paddling pretty hard rn to free up some time to work on my PR in Starlite main, once I get that out of the way I will start reviewing these. Thanks @cofin!

**Comment by cofin** [comment]
No prob.  I think there's still a few additional test cases that need to be added.

Also, sorry about all of the file edits.  If you need me to pull anything out or clarify changes, let me know.

**Comment by v3ss0n** [comment]
Can you guys push a release with just SQLA2.0 dep fix ? it is causing errors to install

**Comment by cofin** [comment]
> Can you guys push a release with just SQLA2.0 dep fix ? it is causing errors to install

This fix is in `main`, I think.

you can try to update your `pyproject.toml` to something like this:
```toml

starlite-saqlalchemy = {git = "https://github.com/topsport-com-au/starlite-saqlalchemy.git", branch = "main", extras = ["cache", "worker", "sqlalchemy", "structlog"]}

```

Then you should re-run `poetry lock && poetry install`

**Comment by v3ss0n** [comment]
Right , i will directly get it from main then. thanks guys.

**Comment by peterschutt** [comment]
> Right , i will directly get it from main then. thanks guys.

Thanks for your patience @v3ss0n - all of my open source time is currently going into starlite v2 - which will have a big downstream impact on this lib, so just want to get that stuff out of the way first.

**Comment by v3ss0n** [comment]
Thats awesome , excited , waiting , and can't wait to upgrade to 2.0 . Don't care about breaking changes , you guys doing awesome job.

**Comment by cofin** [comment]
I'm going to close this PR.  I think it needs to be re-worked now that a chunk of this exists in contrib.

**Pull request closed without merging**
