### PR TITLE
fix(logging): reading empty body when extracting request data

### LINKED ISSUE #208: bug(logging): logging error when using rich
## Description
When using [rich](https://github.com/Textualize/rich) to show pretty tracebacks, errors happens if `exc` is None: https://github.com/topsport-com-au/starlite-saqlalchemy/blob/e6a1d43e91f8772d708f173547a22afdb47c9759/src/starlite_saqlalchemy/log/controller.py#L150.

## Details
Traceback:
```python
Traceback (most recent call last):
  File "/home/gazorby/.cache/pypoetry/virtualenvs/starlite-dev-MVX66ndR-py3.10/lib/python3.10/site-packages/starlite/middleware/exceptions/middleware.py", line 47, in __call__
    await self.app(scope, receive, send)
  File "/home/gazorby/.cache/pypoetry/virtualenvs/starlite-dev-MVX66ndR-py3.10/lib/python3.10/site-packages/starlite/middleware/authentication.py", line 75, in __call__
    await self.app(scope, receive, send)
  File "/home/gazorby/git/perso/starlite-saqlalchemy/src/starlite_saqlalchemy/log/controller.py", line 75, in middleware
    await app(scope, receive, send)
  File "/home/gazorby/.cache/pypoetry/virtualenvs/starlite-dev-MVX66ndR-py3.10/lib/python3.10/site-packages/starlite/middleware/base.py", line 137, in wrapped_call
    await original__call__(self, scope, receive, send)
  File "/home/gazorby/.cache/pypoetry/virtualenvs/starlite-dev-MVX66ndR-py3.10/lib/python3.10/site-packages/starlite/middleware/compression.py", line 147, in __call__
    await self.app(scope, receive, send)
  File "/home/gazorby/.cache/pypoetry/virtualenvs/starlite-dev-MVX66ndR-py3.10/lib/python3.10/site-packages/starlite/middleware/exceptions/middleware.py", line 58, in __call__
    await response(scope=scope, receive=receive, send=send)
  File "/home/gazorby/git/perso/starlite-saqlalchemy/src/starlite_saqlalchemy/log/controller.py", line 151, in __call__
    await LOGGER.aerror("Error in logging before-send handler!", exc_info=exc)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/gazorby/.cache/pypoetry/virtualenvs/starlite-dev-MVX66ndR-py3.10/lib/python3.10/site-packages/structlog/_log_levels.py", line 168, in <lambda>
    lambda: ctx.run(
  File "/home/gazorby/.cache/pypoetry/virtualenvs/starlite-dev-MVX66ndR-py3.10/lib/python3.10/site-packages/structlog/_log_levels.py", line 169, in <lambda>
    lambda: self._proxy_to_logger(name, event, **kw)
  File "/home/gazorby/.cache/pypoetry/virtualenvs/starlite-dev-MVX66ndR-py3.10/lib/python3.10/site-packages/structlog/_base.py", line 205, in _proxy_to_logger
    args, kw = self._process_event(method_name, event, event_kw)
  File "/home/gazorby/.cache/pypoetry/virtualenvs/starlite-dev-MVX66ndR-py3.10/lib/python3.10/site-packages/structlog/_base.py", line 162, in _process_event
    event_dict = proc(self._logger, method_name, event_dict)
  File "/home/gazorby/.cache/pypoetry/virtualenvs/starlite-dev-MVX66ndR-py3.10/lib/python3.10/site-packages/structlog/dev.py", line 424, in __call__
    self._exception_formatter(sio, exc_info)
  File "/home/gazorby/.cache/pypoetry/virtualenvs/starlite-dev-MVX66ndR-py3.10/lib/python3.10/site-packages/structlog/dev.py", line 187, in rich_traceback
    Traceback.from_exception(*exc_info, show_locals=True)
  File "/home/gazorby/.cache/pypoetry/virtualenvs/starlite-dev-MVX66ndR-py3.10/lib/python3.10/site-packages/rich/traceback.py", line 293, in from_exception
    rich_traceback = cls.extract(
  File "/home/gazorby/.cache/pypoetry/virtualenvs/starlite-dev-MVX66ndR-py3.10/lib/python3.10/site-packages/rich/traceback.py", line 354, in extract
    exc_type=safe_str(exc_type.__name__),
AttributeError: 'NoneType' object has no attribute '__name__'
```

### PR DESCRIPTION
**Pull request by gazorby**
Fixes "`Error in logging before-send handler!`" error that occurs when extracting request data with an empty body.

Closes #208 

This fixes simple cases like the following:

```python
from starlite import Controller, NotAuthorizedException, Starlite, post
from starlite_saqlalchemy import ConfigureApp, PluginConfig


class MyController(Controller):
    path: str = "/api"

    @post(path="/")
    async def handle_post(self) -> str:
        raise NotAuthorizedException()

starlite_saqlalchemy_config = PluginConfig(do_worker=False, do_sentry=False)

app = Starlite(
    route_handlers=[MyController],
    on_app_init=[ConfigureApp(config=starlite_saqlalchemy_config)],
)
```

Where logging currently shows:

```console
2023-01-07T20:56:37.464647Z [error    ] Error in logging before-send handler!
NoneType: None
```

Instead of something like:

```console
2023-01-07T21:07:29.957873Z [info     ] HTTP                           request={'path': '/api', 'method': 'POST', 'content_type': ('application/x-www-form-urlencoded', {}), 'headers': {'host': 'localhost:7755', 'user-agent': 'curl/7.87.0', 'accept': '*/*', 'content-length': '15', 'content-type': 'application/x-www-form-urlencoded'}, 'cookies': {}, 'query': b'', 'path_params': {}, 'body': None} response={'status_code': 401, 'cookies': {}, 'headers': {'content-type': 'application/json', 'content-length': '43'}, 'body': b'{"status_code":401,"detail":"Unauthorized"}'}
```

### CODE REVIEW

**Comment by peterschutt** [comment]
thanks @gazorby!

**Comment by peterschutt** [comment]
What is the `.tool-versions` file for? You happy if I `.gitignore` that?

**Comment by gazorby** [comment]
Oh sorry didn't want to push that!
It's a configuration file for [asdf-vm](https://asdf-vm.com/) because I'm still using python 3.10 on my system. It allows me to use 3.11 when working on this project ;)

**Comment by peterschutt** [comment]
OK, cool. I use pyenv for similar but the mulit-tool aspect of that sounds interesting!

**Pull request merged**
